#!/usr/bin/env bash

original_dir=$(pwd)

cd $(dirname $BASH_SOURCE)

npm install

[ -e ../build ] || mkdir ../build

node build.js ../index.html "$@"
[ -e ../build/scripts.js.map ] && (echo "//# sourceMappingURL=scripts.js.map" >> ../build/scripts.js)

maxprocs=$(( $(nproc --all) - 1 ))

function CjC {
	java -jar node_modules/google-closure-compiler/compiler.jar --language_in ECMASCRIPT6 --language_out ECMASCRIPT5 $1 > ${1/../..\/build} &&
	oldsize=$(stat -c %s $1)
	newsize=$(stat -c %s ${1/../..\/build})
	echo Compiled $1: $newsize / $oldsize = $(node -pe "($newsize / $oldsize * 100).toFixed(2)")%
}
export -f CjC

cp -r ../modules ../build
find ../modules/ -name "*.js" | xargs -n1 -P $maxprocs -I{} bash -c "CjC {}"
cp -r ../locales ../build
cp ../manifest.webapp ../build

mkdir -p ../build/scripts/lib
mkdir -p ../build/scripts/parsers/odt.js/lib
echo -n \
	../scripts/messages.js \
	../scripts/lib/codemirror-compressed.js \
	../scripts/lib/socket.io.js \
	../scripts/lib/sjcl.js \
	../scripts/lib/jszip.js \
	../scripts/lib/jszip-deflate.js \
	../scripts/lib/jszip-inflate.js \
	../scripts/lib/jszip-load.js \
	../scripts/lib/jquery.min.js \
	../scripts/lib/spectrum.js \
	../scripts/parsers/plain-text.js \
	../scripts/parsers/odt.js/lib/odt.js \
| xargs -n1 -P $maxprocs -d ' ' -I{} bash -c "CjC {}"

mkdir -p ../build/style/icons/app
mkdir -p ../build/style/lib
cp ../style/icons/app/64.png ../build/style/icons/app
cp ../style/icons/app/128.png ../build/style/icons/app
cp ../style/icons/app/256.png ../build/style/icons/app
cp ../style/icons/app/firetext_christmas.svg ../build/style/icons/app
cp ../style/lib/spectrum.css ../build/style/lib
cp -r ../style/codemirror ../build/style

cd $original_dir