#!/usr/bin/env bash

original_dir=$(pwd)

cd $(dirname $BASH_SOURCE)

npm install

[ -e ../build ] || mkdir ../build

node build.js ../index.html "$@"
[ -e ../build/scripts.js.map ] && (echo "//# sourceMappingURL=scripts.js.map" >> ../build/scripts.js)

function CC {
	echo Compiling $1
	java -jar node_modules/google-closure-compiler/compiler.jar --language_in ECMASCRIPT6 --language_out ECMASCRIPT5 $1 > ${1/../..\/build}
}

cp -r ../modules ../build
for file in $(find ../modules/ -name "*.js"); do
	CC $file
done
cp -r ../locales ../build
cp ../manifest.webapp ../build

mkdir -p ../build/scripts/cloud
mkdir -p ../build/scripts/lib
mkdir -p ../build/scripts/parsers/odt.js/lib
CC ../scripts/messages.js
CC ../scripts/cloud/dropbox.min.js
CC ../scripts/cloud/dropbox_authdriver_firefoxos_receiver.js
CC ../scripts/lib/codemirror-compressed.js
CC ../scripts/lib/socket.io.js
CC ../scripts/lib/sjcl.js
CC ../scripts/lib/jszip.js
CC ../scripts/lib/jszip-deflate.js
CC ../scripts/lib/jszip-inflate.js
CC ../scripts/lib/jszip-load.js
CC ../scripts/lib/stringview.js
CC ../scripts/lib/spectrum.js
CC ../scripts/parsers/plain-text.js
CC ../scripts/parsers/odt.js/lib/odt.js

mkdir -p ../build/style/icons/app
mkdir -p ../build/style/lib
cp ../style/icons/app/64.png ../build/style/icons/app
cp ../style/icons/app/128.png ../build/style/icons/app
cp ../style/icons/app/256.png ../build/style/icons/app
cp ../style/icons/app/firetext_christmas.svg ../build/style/icons/app
cp ../style/lib/spectrum.css ../build/style/lib
cp -r ../style/codemirror ../build/style

cd $original_dir